var fileBrowser = {};
fileBrowser.models = {};
fileBrowser.subsystem = {};
fileBrowser.subsystem.select = {};
fileBrowser.subsystem.fileSorts = {};
fileBrowser.controllers = {}
fileBrowser.controllers.drag = {}
fileBrowser.controllers.mouse = {}
fileBrowser.views = {};
fileBrowser.webSockets = {};