var fileBrowser = {};
fileBrowser.models = {};
fileBrowser.subsystems = {};
fileBrowser.subsystems.selects = {};
fileBrowser.subsystems.fileSorts = {};
fileBrowser.controllers = {}
fileBrowser.controllers.drags = {}
fileBrowser.controllers.mouses = {}
fileBrowser.views = {};
fileBrowser.webSockets = {};